port: 8700

database:
  server: localhost
  name: tfilocaldb
  username: agung
  password: rahasia

cookie: 
  secure: true
  lifetime: 24

template:
  cached: false
  dir: "../data/templates/v2"  

application:
  pagedir: "../data/pages"
  contentdir: "../data/content"

logging:
  enabled: true

  